package rat.poison.utils

import rat.poison.curLocalization

fun GetWeaponsMap(): Settings {
    val WeaponsMap = Settings()
    WeaponsMap[curLocalization["DESERT_EAGLE"]] = "DESERT_EAGLE"
    WeaponsMap[curLocalization["DUAL_BERRETA"]] = "DUAL_BERRETA"
    WeaponsMap[curLocalization["FIVE_SEVEN"]] = "FIVE_SEVEN"
    WeaponsMap[curLocalization["GLOCK"]] = "GLOCK"
    WeaponsMap[curLocalization["AK47"]] = "AK47"
    WeaponsMap[curLocalization["AUG"]] = "AUG"
    WeaponsMap[curLocalization["AWP"]] = "AWP"
    WeaponsMap[curLocalization["FAMAS"]] = "FAMAS"
    WeaponsMap[curLocalization["G3SG1"]] = "G3SG1"
    WeaponsMap[curLocalization["GALIL"]] = "GALIL"
    WeaponsMap[curLocalization["M249"]] = "M249"
    WeaponsMap[curLocalization["M4A4"]] = "M4A4"
    WeaponsMap[curLocalization["MAC10"]] = "MAC10"
    WeaponsMap[curLocalization["P90"]] = "P90"
    WeaponsMap[curLocalization["MP5"]] = "MP5"
    WeaponsMap[curLocalization["UMP45"]] = "UMP45"
    WeaponsMap[curLocalization["XM1014"]] = "XM1014"
    WeaponsMap[curLocalization["PP_BIZON"]] = "PP_BIZON"
    WeaponsMap[curLocalization["MAG7"]] = "MAG7"
    WeaponsMap[curLocalization["NEGEV"]] = "NEGEV"
    WeaponsMap[curLocalization["SAWED_OFF"]] = "SAWED_OFF"
    WeaponsMap[curLocalization["TEC9"]] = "TEC9"
    WeaponsMap[curLocalization["ZEUS_X27"]] = "ZEUS_X27"
    WeaponsMap[curLocalization["P2000"]] = "P2000"
    WeaponsMap[curLocalization["MP7"]] = "MP7"
    WeaponsMap[curLocalization["MP9"]] = "MP9"
    WeaponsMap[curLocalization["NOVA"]] = "NOVA"
    WeaponsMap[curLocalization["P250"]] = "P250"
    WeaponsMap[curLocalization["SCAR20"]] = "SCAR20"
    WeaponsMap[curLocalization["SG553"]] = "SG553"
    WeaponsMap[curLocalization["SSG08"]] = "SSG08"
    WeaponsMap[curLocalization["KNIFE"]] = "KNIFE"
    WeaponsMap[curLocalization["FLASH_GRENADE"]] = "FLASH_GRENADE"
    WeaponsMap[curLocalization["EXPLOSIVE_GRENADE"]] = "EXPLOSIVE_GRENADE"
    WeaponsMap[curLocalization["SMOKE_GRENADE"]] = "SMOKE_GRENADE"
    WeaponsMap[curLocalization["MOLOTOV"]] = "MOLOTOV"
    WeaponsMap[curLocalization["DECOY_GRENADE"]] = "DECOY_GRENADE"
    WeaponsMap[curLocalization["INCENDIARY_GRENADE"]] = "INCENDIARY_GRENADE"
    WeaponsMap[curLocalization["C4"]] = "C4"
    WeaponsMap[curLocalization["MEDISHOT"]] = "MEDISHOT"
    WeaponsMap[curLocalization["KNIFE_T"]] = "KNIFE_T"
    WeaponsMap[curLocalization["M4A1_SILENCER"]] = "M4A1_SILENCER"
    WeaponsMap[curLocalization["USP_SILENCER"]] = "USP_SILENCER"
    WeaponsMap[curLocalization["CZ75A"]] = "CZ75A"
    WeaponsMap[curLocalization["R8_REVOLVER"]] = "R8_REVOLVER"
    WeaponsMap[curLocalization["FISTS"]] = "FISTS"
    WeaponsMap[curLocalization["CHARGE"]] = "CHARGE"
    WeaponsMap[curLocalization["TABLET"]] = "TABLET"
    WeaponsMap[curLocalization["HAMMER"]] = "HAMMER"
    WeaponsMap[curLocalization["FIRE_BOMB"]] = "FIRE_BOMB"
    WeaponsMap[curLocalization["DIVERSION_DEVICE"]] = "DIVERSION_DEVICE"
    WeaponsMap[curLocalization["KNIFE_BAYONET"]] = "KNIFE_BAYONET"
    WeaponsMap[curLocalization["KNIFE_CSS"]] = "KNIFE_CSS"
    WeaponsMap[curLocalization["KNIFE_FLIP"]] = "KNIFE_FLIP"
    WeaponsMap[curLocalization["KNIFE_GUT"]] = "KNIFE_GUT"
    WeaponsMap[curLocalization["KNIFE_KARAMBIT"]] = "KNIFE_KARAMBIT"
    WeaponsMap[curLocalization["KNIFE_M9_BAYONET"]] = "KNIFE_M9_BAYONET"
    WeaponsMap[curLocalization["KNIFE_TACTICAL"]] = "KNIFE_TACTICAL"
    WeaponsMap[curLocalization["KNIFE_FALCHION"]] = "KNIFE_FALCHION"
    WeaponsMap[curLocalization["KNIFE_BOWIE"]] = "KNIFE_BOWIE"
    WeaponsMap[curLocalization["KNIFE_BUTTERFLY"]] = "KNIFE_BUTTERFLY"
    WeaponsMap[curLocalization["KNIFE_PUSH"]] = "KNIFE_PUSH"
    WeaponsMap[curLocalization["KNIFE_CORD"]] = "KNIFE_CORD"
    WeaponsMap[curLocalization["KNIFE_CANIS"]] = "KNIFE_CANIS"
    WeaponsMap[curLocalization["KNIFE_URSUS"]] = "KNIFE_URSUS"
    WeaponsMap[curLocalization["KNIFE_GYPSY"]] = "KNIFE_GYPSY"
    WeaponsMap[curLocalization["KNIFE_OUTDOOR"]] = "KNIFE_OUTDOOR"
    WeaponsMap[curLocalization["KNIFE_STILETTO"]] = "KNIFE_STILETTO"
    WeaponsMap[curLocalization["KNIFE_WIDOWMAKER"]] = "KNIFE_WIDOWMAKER"
    WeaponsMap[curLocalization["KNIFE_SKELETON"]] = "KNIFE_SKELETON"
    return WeaponsMap
}