package rat.poison.utils

import rat.poison.curLocalization
import rat.poison.utils.Settings

fun GetWeaponsMap(): Settings {
    val WeaponsMap = Settings()
    WeaponsMap["DESERT_EAGLE"] = curLocalization["DESERT_EAGLE"]
    WeaponsMap["DUAL_BERRETA"] = curLocalization["DUAL_BERRETA"]
    WeaponsMap["FIVE_SEVEN"] = curLocalization["FIVE_SEVEN"]
    WeaponsMap["GLOCK"] = curLocalization["GLOCK"]
    WeaponsMap["AK47"] = curLocalization["AK47"]
    WeaponsMap["AUG"] = curLocalization["AUG"]
    WeaponsMap["AWP"] = curLocalization["AWP"]
    WeaponsMap["FAMAS"] = curLocalization["FAMAS"]
    WeaponsMap["G3SG1"] = curLocalization["G3SG1"]
    WeaponsMap["GALIL"] = curLocalization["GALIL"]
    WeaponsMap["M249"] = curLocalization["M249"]
    WeaponsMap["M4A4"] = curLocalization["M4A4"]
    WeaponsMap["MAC10"] = curLocalization["MAC10"]
    WeaponsMap["P90"] = curLocalization["P90"]
    WeaponsMap["MP5"] = curLocalization["MP5"]
    WeaponsMap["UMP45"] = curLocalization["UMP45"]
    WeaponsMap["XM1014"] = curLocalization["XM1014"]
    WeaponsMap["PP_BIZON"] = curLocalization["PP_BIZON"]
    WeaponsMap["MAG7"] = curLocalization["MAG7"]
    WeaponsMap["NEGEV"] = curLocalization["NEGEV"]
    WeaponsMap["SAWED_OFF"] = curLocalization["SAWED_OFF"]
    WeaponsMap["TEC9"] = curLocalization["TEC9"]
    WeaponsMap["ZEUS_X27"] = curLocalization["ZEUS_X27"]
    WeaponsMap["P2000"] = curLocalization["P2000"]
    WeaponsMap["MP7"] = curLocalization["MP7"]
    WeaponsMap["MP9"] = curLocalization["MP9"]
    WeaponsMap["NOVA"] = curLocalization["NOVA"]
    WeaponsMap["P250"] = curLocalization["P250"]
    WeaponsMap["SCAR20"] = curLocalization["SCAR20"]
    WeaponsMap["SG553"] = curLocalization["SG553"]
    WeaponsMap["SSG08"] = curLocalization["SSG08"]
    WeaponsMap["KNIFE"] = curLocalization["KNIFE"]
    WeaponsMap["FLASH_GRENADE"] = curLocalization["FLASH_GRENADE"]
    WeaponsMap["EXPLOSIVE_GRENADE"] = curLocalization["EXPLOSIVE_GRENADE"]
    WeaponsMap["SMOKE_GRENADE"] = curLocalization["SMOKE_GRENADE"]
    WeaponsMap["MOLOTOV"] = curLocalization["MOLOTOV"]
    WeaponsMap["DECOY_GRENADE"] = curLocalization["DECOY_GRENADE"]
    WeaponsMap["INCENDIARY_GRENADE"] = curLocalization["INCENDIARY_GRENADE"]
    WeaponsMap["C4"] = curLocalization["C4"]
    WeaponsMap["MEDISHOT"] = curLocalization["MEDISHOT"]
    WeaponsMap["KNIFE_T"] = curLocalization["KNIFE_T"]
    WeaponsMap["M4A1_SILENCER"] = curLocalization["M4A1_SILENCER"]
    WeaponsMap["USP_SILENCER"] = curLocalization["USP_SILENCER"]
    WeaponsMap["CZ75A"] = curLocalization["CZ75A"]
    WeaponsMap["R8_REVOLVER"] = curLocalization["R8_REVOLVER"]
    WeaponsMap["FISTS"] = curLocalization["FISTS"]
    WeaponsMap["CHARGE"] = curLocalization["CHARGE"]
    WeaponsMap["TABLET"] = curLocalization["TABLET"]
    WeaponsMap["HAMMER"] = curLocalization["HAMMER"]
    WeaponsMap["FIRE_BOMB"] = curLocalization["FIRE_BOMB"]
    WeaponsMap["DIVERSION_DEVICE"] = curLocalization["DIVERSION_DEVICE"]
    WeaponsMap["KNIFE_BAYONET"] = curLocalization["KNIFE_BAYONET"]
    WeaponsMap["KNIFE_CSS"] = curLocalization["KNIFE_CSS"]
    WeaponsMap["KNIFE_FLIP"] = curLocalization["KNIFE_FLIP"]
    WeaponsMap["KNIFE_GUT"] = curLocalization["KNIFE_GUT"]
    WeaponsMap["KNIFE_KARAMBIT"] = curLocalization["KNIFE_KARAMBIT"]
    WeaponsMap["KNIFE_M9_BAYONET"] = curLocalization["KNIFE_M9_BAYONET"]
    WeaponsMap["KNIFE_TACTICAL"] = curLocalization["KNIFE_TACTICAL"]
    WeaponsMap["KNIFE_FALCHION"] = curLocalization["KNIFE_FALCHION"]
    WeaponsMap["KNIFE_BOWIE"] = curLocalization["KNIFE_BOWIE"]
    WeaponsMap["KNIFE_BUTTERFLY"] = curLocalization["KNIFE_BUTTERFLY"]
    WeaponsMap["KNIFE_PUSH"] = curLocalization["KNIFE_PUSH"]
    WeaponsMap["KNIFE_CORD"] = curLocalization["KNIFE_CORD"]
    WeaponsMap["KNIFE_CANIS"] = curLocalization["KNIFE_CANIS"]
    WeaponsMap["KNIFE_URSUS"] = curLocalization["KNIFE_URSUS"]
    WeaponsMap["KNIFE_GYPSY"] = curLocalization["KNIFE_GYPSY"]
    WeaponsMap["KNIFE_OUTDOOR"] = curLocalization["KNIFE_OUTDOOR"]
    WeaponsMap["KNIFE_STILETTO"] = curLocalization["KNIFE_STILETTO"]
    WeaponsMap["KNIFE_WIDOWMAKER"] = curLocalization["KNIFE_WIDOWMAKER"]
    WeaponsMap["KNIFE_SKELETON"] = curLocalization["KNIFE_SKELETON"]
    return WeaponsMap
}