package rat.poison.settings

var BONE_TRIGGER_FOV = 12
var BONE_TRIGGER_BONE = HEAD_BONE
var AIM_ON_BONE_TRIGGER = true
var BONE_TRIGGER_ENABLE_KEY = false
var BONE_TRIGGER_KEY = 6
var BONE_TRIGGER_SHOT_DELAY = 8