package rat.poison.game

@Suppress("unused")
enum class Weapons(val id: Int, val gun: Boolean = false, val automatic: Boolean = false, val grenade: Boolean = false,
                   val knife: Boolean = false, val miscEnt: Boolean = false, val bomb: Boolean = false, val sniper: Boolean = false, val boltAction: Boolean = false,
                   val pistol: Boolean = false, val shotgun: Boolean = false, val rifle: Boolean = false, val smg: Boolean = false, val scope: Boolean = false) {
	
	NONE(0),
	DESERT_EAGLE(1, gun = true, pistol = true),
	DUAL_BERETTA(2, gun = true, pistol = true),
	FIVE_SEVEN(3, gun = true, pistol = true),
	GLOCK(4, gun = true, pistol = true),
	AK47(7, gun = true, automatic = true, rifle = true),
	AUG(8, gun = true, automatic = true, rifle = true, scope = true),
	AWP(9, gun = true, sniper = true, boltAction = true, scope = true),
	FAMAS(10, gun = true, automatic = true, rifle = true),
	G3SG1(11, gun = true, sniper = true, scope = true),
	GALIL(13, gun = true, automatic = true, rifle = true),
	M249(14, gun = true, automatic = true, rifle = true),
	M4A4(16, gun = true, automatic = true, rifle = true),
	MAC10(17, gun = true, automatic = true, smg = true),
	P90(19, gun = true, automatic = true, smg = true),
	MP5(23, gun = true, automatic = true, smg = true),
	UMP45(24, gun = true, automatic = true, smg = true),
	XM1014(25, gun = true, automatic = true, shotgun = true),
	PP_BIZON(26, gun = true, automatic = true, smg = true),
	MAG7(27, gun = true, boltAction = true, shotgun = true),
	NEGEV(28, gun = true, automatic = true, rifle = true),
	SAWED_OFF(29, gun = true, boltAction = true, shotgun = true),
	TEC9(30, gun = true, pistol = true),
	ZEUS_X27(31, pistol = true),
	P2000(32, gun = true, pistol = true),
	MP7(33, gun = true, automatic = true, smg = true),
	MP9(34, gun = true, automatic = true, smg = true),
	NOVA(35, gun = true, boltAction = true, shotgun = true),
	P250(36, gun = true, pistol = true),
	SCAR20(38, gun = true, sniper = true, scope = true),
	SG553(39, gun = true, automatic = true, rifle = true, scope = true),
	SSG08(40, gun = true, sniper = true, boltAction = true, scope = true),
	KNIFE(42, knife = true),
	FLASH_GRENADE(43, grenade = true),
	EXPLOSIVE_GRENADE(44, grenade = true),
	SMOKE_GRENADE(45, grenade = true),
	MOLOTOV(46, grenade = true),
	DECOY_GRENADE(47, grenade = true),
	INCENDIARY_GRENADE(48, grenade = true),
	C4(49, bomb = true),
	MEDISHOT(57, miscEnt = true),
	KNIFE_T(59, knife = true),
	M4A1_SILENCER(60, gun = true, automatic = true, rifle = true),
	USP_SILENCER(61, gun = true, pistol = true),
	CZ75A(63, gun = true, automatic = true, pistol = true),
	R8_REVOLVER(64, gun = true, boltAction = true, pistol = true, automatic = true),
	FISTS(69, miscEnt = true),
	CHARGE(70, miscEnt = true),
	TABLET(72, miscEnt = true),
	HAMMER(76, miscEnt = true),
	FIRE_BOMB(81, miscEnt = true),
	DIVERSION_DEVICE(82, miscEnt = true),
	KNIFE_BAYONET(500, knife = true),
	KNIFE_CSS(503, knife = true),
	KNIFE_FLIP(505, knife = true),
	KNIFE_GUT(506, knife = true),
	KNIFE_KARAMBIT(507, knife = true),
	KNIFE_M9_BAYONET(508, knife = true),
	KNIFE_TACTICAL(509, knife = true),
	KNIFE_FALCHION(512, knife = true),
	KNIFE_BOWIE(514, knife = true),
	KNIFE_BUTTERFLY(515, knife = true),
	KNIFE_PUSH(516, knife = true),
	KNIFE_CORD(517, knife = true),
	KNIFE_CANIS(518, knife = true),
	KNIFE_URSUS(519, knife = true),
	KNIFE_GYPSY(520, knife = true),
	KNIFE_OUTDOOR(521, knife = true),
	KNIFE_STILETTO(522, knife = true),
	KNIFE_WIDOWMAKER(523, knife = true),
	KNIFE_SKELETON(525, knife = true);
	
	companion object {
		private val cachedValues = values()
		operator fun get(id: Int) = cachedValues.firstOrNull { it.id == id } ?: NONE
	}
}